---
# tasks file for neutron

- name: Creating Neutron user
  shell: openstack user create --domain default --password {{ mysql_service_pass }} neutron

- name: Adding Neutron user to admin role
  shell: openstack role add --project service --user neutron admin


- name: Creating Network service
  shell: openstack service create --name neutron  --description "OpenStack Networking" network

- name: Creating Network EndPoints
  shell: "openstack endpoint create --region RegionOne network {{ item }} http://controller:9696"
  with_items:
    - public
    - internal
    - admin

- name: Installing Packages
  yum:
    name: ['openstack-neutron' ,'openstack-neutron-ml2' ,'openstack-neutron-linuxbridge' ,'ebtables','ipset']
    state: present

- name: Configuring Network Service
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf

- name: Configuring Layer2 Networking
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini

- name: Configuring the linux bridge
  template:
    src: linuxbridge_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: Configuring the L3 Networking
  template:
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini


- name: Configuring DHCP
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini

- name: Configuring MetaData Agent
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini

- name: enabling Layer2 
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link

- name: Populating the DB
  shell: /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron

- name: Restarting NOVA
  service:
    name: openstack-nova-api
    state: restarted

- name: enabling and starting Network Services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent
