---
# tasks file for horizon

- name: Installing Horizon
  yum:
    name: openstack-dashboard
    state: present

- name: Configuring Horizon local_settings 
  template:
    src: local_settings.j2
    dest: /etc/openstack-dashboard/local_settings


- name: Configuring Httpd
  template:
    src: openstack-dashboard.conf.j2
    dest: /etc/httpd/conf.d/openstack-dashboard.conf

- name: Restarting http and memcached services
  service:  
    name: "{{ item }}"
    state: restarted
  with_items:
    - httpd
    - memcached
