---
# tasks file for memcached
- name: Installing memcached
  yum:
    name: ['memcached' ,'python-memcached']
    state: present


- name: Canging config
  lineinfile:
    path: /etc/sysconfig/memcached
    regexp: "^OPTIONS"
    line: OPTIONS="-l 127.0.0.1,::1,controller"

- name: starting and enabling memcached
  service:
   name: memcached
   state: started
   enabled: yes


